### ISSUE TITLE
BrokenPipe ... better output

### ISSUE THREAD

**Issue by ondratu** [PoorHttp/PoorWSGI#19]
```
ERROR: Error for client 10.24.223.248 {handle_error():17}
#012Traceback (most recent call last):
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 138, in run
#012 self.finish_response()
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
#012 self.write(data)
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 274, in write
#012 self.send_headers()
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 332, in send_headers
#012 self.send_preamble()
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 255, in send_preamble
#012 ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 453, in _write
#012 result = self.stdout.write(data)
#012 File "/usr/lib/python3.7/socketserver.py", line 799, in write
#012 self._sock.sendall(b)
#012BrokenPipeError: [Errno 32] Broken pipe
#012
#012During handling of the above exception, another exception occurred:
#012
#012Traceback (most recent call last):
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 141, in run
#012 self.handle_error()
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
#012 self.finish_response()
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
#012 self.write(data)
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 274, in write
#012 self.send_headers()
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
#012 if not self.origin_server or self.client_is_modern():
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
#012 return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
#012TypeError: 'NoneType' object is not subscriptable
#012
#012During handling of the above exception, another exception occurred:
#012
#012Traceback (most recent call last):
#012 File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
#012 self.finish_request(request, client_address)
#012 File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
#012 self.RequestHandlerClass(request, client_address, self)
#012 File "/usr/lib/python3.7/socketserver.py", line 720, in _init_
#012 self.handle()
#012 File "/usr/lib/python3.7/wsgiref/simple_server.py", line 133, in handle
#012 handler.run(self.server.get_app())
#012 File "/usr/lib/python3.7/wsgiref/handlers.py", line 144, in run
#012 self.close()
#012 File "/usr/lib/python3.7/wsgiref/simple_server.py", line 35, in close
#012 self.status.split(' ',1)[0], self.bytes_sent
#012AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ondratu** [comment]
This issue cannot be fixed because the current Python wsgiref server operates differently.
